# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'YourName' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # ⚛️ Reactive X
  pod 'RxCocoa'
  pod 'RxDataSources'
  pod 'RxGesture'
  pod 'RxOptional'
  pod 'RxSwift'
  pod 'RxViewController'

  # 🖼 Image Cache
  pod 'Kingfisher'

  # 📐 Layout
  pod 'SnapKit'

  # 🐝 Syntax Sugar
  pod 'Then'
  
  # 🐛 Debug Tool
  pod 'FLEX', :configurations => ['Debug']
  
  # 🥸 Mock
  # pod "Cuckoo"

  target 'YourNameTests' do
    pod 'RxTest'
    pod 'RxBlocking'
    pod 'Quick'
    pod 'Nimble'
  end

end
