# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'YourName' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # ⚛️ Reactive X
  pod 'RxCocoa','~>5.0'
  pod 'RxDataSources','~>4.0'
  pod 'RxGesture','~>3.0'
  pod 'RxOptional','~>4.0'
  pod 'RxSwift','~>5.0'
  pod 'RxViewController','~>1.0'

  # 🖼 Image Cache
  pod 'Kingfisher'

  # 📐 Layout
  pod 'SnapKit'

  # 🐝 Syntax Sugar
  pod 'Then'
  
  # 🐛 Debug Tool
  pod 'FLEX', :configurations => ['Debug']
  
  # 🥸 Mock
  # pod "Cuckoo"

  # 💛 KaKao
  pod 'RxKakaoSDKUser'
  
  target 'YourNameTests' do
    pod 'RxTest','~>5.0'
    pod 'RxBlocking','~>5.0'
    pod 'Quick'
    pod 'Nimble'
  end

end
